### ISSUE TITLE
Support nuxt: Authentication error

### ISSUE THREAD

**Issue by tobiasdiez** [ForestAdmin/agent-nodejs#398]
## Expected behavior

It works

## Actual behavior

Get the following error on every `forest` route:
```
===== An exception was raised =====
GET /_admin/forest/authentication?{}

 Authentication Error 

UnauthorizedError: Authentication Error
    at Object.throw (/workspaces/JabRefOnline/node_modules/koa/lib/context.js:97:11)
    at jwt (/workspaces/JabRefOnline/node_modules/koa-jwt/lib/index.js:23:22)
    at dispatch (/workspaces/JabRefOnline/node_modules/koa-compose/index.js:42:32)
    at /workspaces/JabRefOnline/node_modules/@koa/router/lib/router.js:372:16
    at dispatch (/workspaces/JabRefOnline/node_modules/koa-compose/index.js:42:32)
    at ErrorHandling.errorHandler (/workspaces/JabRefOnline/node_modules/@forestadmin/agent/dist/agent/routes/system/error-handling.js:20:19)
    at dispatch (/workspaces/JabRefOnline/node_modules/koa-compose/index.js:42:32)
    at /workspaces/JabRefOnline/node_modules/@koa/router/lib/router.js:372:16
    at dispatch (/workspaces/JabRefOnline/node_modules/koa-compose/index.js:42:32)
    at Logger.logger (/workspaces/JabRefOnline/node_modules/@forestadmin/agent/dist/agent/routes/system/logger.js:19:19)
===================================
```

## Context

I'm trying to embed ForestAdmin in a Nuxt v3 application. I know this is currently not supported, but I thought I give it a shot nonetheless. The code is

``` ts
import { createAgent } from '@forestadmin/agent'
import { createSqlDataSource } from '@forestadmin/datasource-sql'
import { Environment } from '~/config'

export default defineLazyEventHandler(async () => {
  const config = useRuntimeConfig()
  // Create your Forest Admin agent
  const agent = createAgent({
    // These process.env variables should be provided in the onboarding
    authSecret: process.env.FOREST_AUTH_SECRET,
    agentUrl: 'http://localhost:3000/_admin/', // process.env.FOREST_AGENT_URL,
    envSecret: process.env.FOREST_ENV_SECRET,
    isProduction: false,
  }).addDataSource(createSqlDataSource(process.env.DATABASE_URL))
  const callback = agent.getConnectCallback(false)
  await agent.start()

  return toEventHandler(callback)
})
``` 
Which is pretty close to the other supported hostings (e.g. express). I'm willing to debug this further, but I need a bit of assistance. For example, what kind of jwt tokens are expected and how are they usually provided? Why is it checking for a jwt token on every route? 

- Package Version: latest beta

**Comment by romain-gilliotte** [comment]
I'm closing this as we had no news about it since august
