### ISSUE TITLE
Special characters in prefix lead to errors

### ISSUE THREAD

**Issue by tobiasdiez** [ForestAdmin/agent-nodejs#399]
## Expected behavior

It works

## Actual behavior

Get the following error
```
Error: options.prefix is invalid. It should contain the prefix on which forest admin routes should be mounted (i.e. "/api/v1")
    at OptionsValidator.checkOtherOptions (/workspaces/JabRefOnline/node_modules/@forestadmin/agent/dist/builder/utils/options-validator.js:76:19)
    at OptionsValidator.validate (/workspaces/JabRefOnline/node_modules/@forestadmin/agent/dist/builder/utils/options-validator.js:35:26)
    at AgentBuilder.start (/workspaces/JabRefOnline/node_modules/@forestadmin/agent/dist/builder/agent.js:198:53)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

## Context

Set `prefix: '_admin'`. After removing the regex check at https://github.com/ForestAdmin/agent-nodejs/blob/4b21ca78a4b46d748c8f853e22490c81e6a6bbd3/packages/agent/src/builder/utils/options-validator.ts#L110 it works well, so I think the regex needs to be modified to allow for `_`.

- Package Version:

**Comment by jeffladiray** [comment]
Hey @tobiasdiez, and thanks for reporting this issue. I'm able to reproduce as well.

I'll file a ticket in our internal bug tracker, and I'll let you know once release 👍
