### ISSUE TITLE
Issue with path-to-regexp library

### ISSUE THREAD

**Issue by Segfaultd** [ForestAdmin/agent-nodejs#418]
### Introduction

It's me again. I've been trying to integrate agent into raw Express application, and struggling for a few hours with an error

```
TypeError: pathToRegexp is not a function
    at new Layer (/Users/admin/dev/mytest/backend/node_modules/@koa/router/lib/layer.js:43:17)
    at Router.register (/Users/admin/dev/mytest/backend/node_modules/@koa/router/lib/router.js:570:17)
    at Router.all (/Users/admin/dev/mytest/backend/node_modules/@koa/router/lib/router.js:501:8)
    at ForestAdminHttpDriver.getRouter (/Users/admin/dev/mytest/backend/node_modules/@forestadmin/agent/src/agent/forestadmin-http-driver.ts:29:12)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at AgentBuilder.start (/Users/admin/dev/mytest/backend/node_modules/@forestadmin/agent/src/builder/agent.ts:229:20)
    at main (/Users/admin/dev/mytest/backend/src/app.ts:108:5)

Issue is that Forest Admin use / include Koa Router that rely on a newer version of the path-to-regexp library than Express 4 does.

Running `npm ls path-to-regexp` return the following

```
├─┬ @forestadmin/agent@1.0.0-beta.55
│ └─┬ @koa/router@10.1.1
│   └── path-to-regexp@6.2.1
└─┬ express@4.17.1
  └── path-to-regexp@0.1.7
```

Issue is that Express already stated they won't upgrade the version they use in a retro compatibility mindset.

Any idea on how to deal with that very specific edge case?

Thanks!

**Comment by Segfaultd** [comment]
Having the following in package.json will fix the compilation & typing issue

```
"resolutions": {
    "express/path-to-regexp": "^0.1.7"
  },
  "overrides": {
    "express": {
      "path-to-regexp": "^0.1.7"
    }
  }```


But so far, the Forest Agent does not work. It binds, but when trying to call authentication route, it will never answer.

**Comment by romain-gilliotte** [comment]
Hi @Segfaultd 

The two versions of pathToRegexp should coexist peacefully :-(
We have a working project using express@4.18 and everything is working

Can you give me more information so that I can find a way to reproduce?

**Comment by Segfaultd** [comment]
Hello @romain-gilliotte and thank you for your answer.

So far, here are the dependencies of the project:

```
"dependencies": {
    "@bull-board/api": "^4.3.1",
    "@bull-board/express": "^4.3.1",
    "@forestadmin/agent": "^1.0.0-beta.57",
    "@forestadmin/datasource-sql": "^1.0.0-beta.50",
    "@forestadmin/datasource-toolkit": "^1.0.0-beta.32",
    "@prisma/client": "^2.18.0",
    "@sentry/node": "^7.12.1",
    "@sentry/tracing": "^7.12.1",
    "@slack/web-api": "^6.7.2",
    "@types/bcrypt": "^5.0.0",
    "@types/bull": "^3.15.9",
    "@types/cron": "^2.0.0",
    "@types/js-yaml": "^4.0.5",
    "@types/jsonwebtoken": "^8.5.9",
    "@types/moment-timezone": "^0.5.30",
    "@types/node-cron": "^3.0.4",
    "@types/node-fetch": "^2.6.2",
    "@types/nodemailer": "^6.4.6",
    "@types/nodemon": "^1.19.2",
    "@types/stripe": "^8.0.417",
    "@types/uuid": "^8.3.4",
    "@types/xml2js": "^0.4.11",
    "add": "^2.0.6",
    "axios": "^0.27.2",
    "bcrypt": "^5.0.0",
    "bull": "^4.9.0",
    "celebrate": "^15.0.1",
    "color-support": "^1.1.3",
    "config": "^3.3.8",
    "cookie-parser": "^1.4.6",
    "cookieparser": "^0.1.0",
    "cors": "^2.8.5",
    "cron": "^2.1.0",
    "cross-env": "^7.0.2",
    "crypto": "^1.0.1",
    "dayjs": "^1.11.5",
    "db-migrate": "^0.11.13",
    "db-migrate-pg": "^1.2.2",
    "debug": "^4.1.1",
    "dotenv": "^16.0.2",
    "easy-soap-request": "^4.8.0",
    "express": "^4.18.1",
    "express-session": "^1.17.3",
    "facebook-nodejs-business-sdk": "^14.0.0",
    "fetch": "^1.1.0",
    "handlebars": "^4.7.7",
    "helmet": "^6.0.0",
    "joi": "^17.6.0",
    "joi-phone-number": "^5.1.1",
    "joi-phone-validator": "^1.0.0",
    "jsonwebtoken": "^8.5.1",
    "moment": "^2.29.2",
    "moment-timezone": "^0.5.32",
    "morgan": "^1.10.0",
    "node-cron": "^3.0.2",
    "node-fetch": "^3.2.10",
    "nodemailer": "^6.7.8",
    "nodemon": "^2.0.19",
    "pm2": "^5.2.0",
    "prisma": "^2.30.3",
    "redis": "^4.3.1",
    "sib-api-v3-sdk": "^8.4.2",
    "sib-api-v3-typescript": "^2.2.0",
    "stripe": "^10.8.0",
    "tslint": "^6.1.3",
    "uuid": "^9.0.0",
    "xml2js": "^0.4.23"
  },
  "devDependencies": {
    "@types/config": "3.3.0",
    "@types/cookie-parser": "^1.4.3",
    "@types/cors": "^2.8.7",
    "@types/debug": "^4.1.5",
    "@types/dotenv": "^8.2.0",
    "@types/express": "^4.17.14",
    "@types/express-session": "^1.17.5",
    "@types/helmet": "4.0.0",
    "@types/jest": "^29.0.2",
    "@types/morgan": "^1.9.1",
    "@types/newrelic": "^7.0.3",
    "@types/node": "^18.7.18",
    "jest": "^29.0.3",
    "mockdate": "^3.0.5",
    "ts-jest": "^29.0.1",
    "ts-loader": "^9.3.1",
    "ts-node": "^10.9.1",
    "tsc-alias": "^1.7.0",
    "tsconfig-paths": "^4.0.0",
    "typescript": "^4.8.3"
  }
```

They are all up-to-date, except prisma and types of prisma, which is intentional.

Node version used is `v14.18.2`

And still struggling with the same issue so far :(

```
yarn run v1.22.19
$ nodemon
[nodemon] 2.0.19
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src/**/* .env
[nodemon] watching extensions: js,ts,json
[nodemon] starting `node --inspect=0.0.0.0:9222 -r ts-node/register/transpile-only -r tsconfig-paths/register ./src/app.ts`
Debugger listening on ws://0.0.0.0:9222/18fae825-39b1-4e56-bad7-43da367918e6
For help, see: https://nodejs.org/en/docs/inspector
info The preview flags `transaction` were removed, you can now safely remove them from your schema.prisma.
info: Successfully mounted on Express.js
info: Schema was not updated since last run
(node:23086) UnhandledPromiseRejectionWarning: TypeError: pathToRegexp is not a function
    at new Layer (/Users/admin/dev/test/backend/node_modules/@koa/router/lib/layer.js:43:17)
    at Router.register (/Users/admin/dev/test/backend/node_modules/@koa/router/lib/router.js:570:17)
    at Router.all (/Users/admin/dev/test/backend/node_modules/@koa/router/lib/router.js:501:8)
    at ForestAdminHttpDriver.getRouter (/Users/admin/dev/test/backend/node_modules/@forestadmin/agent/src/agent/forestadmin-http-driver.ts:29:12)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async AgentBuilder.start (/Users/admin/dev/test/backend/node_modules/@forestadmin/agent/src/builder/agent.ts:228:20)
    at async main (/Users/admin/dev/test/backend/src/app.ts:106:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:23086) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:23086) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by romain-gilliotte** [comment]
I'll try to replicate and come back to you

**Comment by Segfaultd** [comment]
Alright. More debug from my side: it seems nodemon is kinda struggling with the whole thing. I tried to build the solution then run using "node dist/app.js".

Project runs, schema is uploaded to Forest, but when the authenticate call is sent from web app, it returns 500 and the server says the following:

```
yarn run v1.22.19
$ tslint -c tslint.json -p tsconfig.json --fix
$ tsc && tsc-alias && cp -rf package.json dist/package.json
✨  Done in 6.09s.
info The preview flags `transaction` were removed, you can now safely remove them from your schema.prisma.
info: Successfully mounted on Express.js
info: Schema was not updated since last run

  InternalServerError: stream is not readable
      at readStream (/Users/admin/dev/test/backend/node_modules/raw-body/index.js:178:17)
      at executor (/Users/admin/dev/test/backend/node_modules/raw-body/index.js:113:5)
      at new Promise (<anonymous>)
      at getRawBody (/Users/admin/dev/test/backend/node_modules/raw-body/index.js:112:10)
      at AsyncFunction.module.exports [as json] (/Users/admin/dev/test/backend/node_modules/co-body/lib/json.js:39:21)
      at parseBody (/Users/admin/dev/test/backend/node_modules/koa-bodyparser/index.js:100:26)
      at bodyParser (/Users/admin/dev/test/backend/node_modules/koa-bodyparser/index.js:85:25)
      at dispatch (/Users/admin/dev/test/backend/node_modules/koa-compose/index.js:42:32)
      at /Users/admin/dev/test/backend/node_modules/@koa/router/lib/router.js:372:16
      at dispatch (/Users/admin/dev/test/backend/node_modules/koa-compose/index.js:42:32)
```

**Comment by romain-gilliotte** [comment]
can you show me how is your agent mounted on the express app?
it should be first, before other middlewares, as we use our own body parser / cors / etc... for everything that is under the `/forest` prefix.

**Comment by Segfaultd** [comment]
You're right. I moved the whole definitions before mine and now it works. 

Only thing left is to get nodemon working with the custom package overrides.

**Comment by romain-gilliotte** [comment]
I think their is conflict between types exported by the two versions of pathToRegexp

Can you try to

1. remove the package override
2. add `skipLibCheck: true` on your tsconfig

**Comment by Segfaultd** [comment]
I'll check that!

By the way, any idea why any webapp call triggers the following on my backend:

`Roles V2 are unsupported` ? 😄

**Comment by romain-gilliotte** [comment]
Yes!

Please read the following thread
https://community.forestadmin.com/t/permissions-errors-getting-collections/5177/18

**Comment by Segfaultd** [comment]
Alright got it. Thank you. I'll keep you updated for the rest of the debugging. Thanks for the help 💪🏻

**Comment by romain-gilliotte** [comment]
Is everything working so that I can close this issue?
