### ISSUE TITLE
I can't retrieve any data, got error `Failed Dependency`

### ISSUE THREAD

**Issue by ajubin** [ForestAdmin/agent-nodejs#554]
## Expected behavior

I'd like to start the server and see the data in my db

## Actual behavior

When I start the agent with my current database, the server starts, but on Forest Admin I can't see any data

<img width="1449" alt="image" src="https://user-images.githubusercontent.com/14874974/203347531-a6ec22fb-22c6-4340-91b9-d44fd6ab0fd4.png">

This is how I start my server, I don't know how to debug this

```ts
require('dotenv/config');

import { createAgent } from '@forestadmin/agent';
import { createSqlDataSource } from '@forestadmin/datasource-sql';
import { env } from 'process';
import { z } from 'zod';

const ENV = z
  .object({
    FOREST_AUTH_SECRET: z.string().min(1),
    FOREST_ENV_SECRET: z.string().min(1),
    NODE_ENV: z.string().optional(),
    DATABASE_URL: z.string().min(1),
  })
  .parse(env);

async function bootstrap() {
  const marketplaceDatasource = createSqlDataSource(ENV.DATABASE_URL);
  const agent = createAgent({
    authSecret: ENV.FOREST_AUTH_SECRET,
    envSecret: ENV.FOREST_ENV_SECRET,
    isProduction: ENV.NODE_ENV === 'production',
  }).addDataSource(marketplaceDatasource, {
    include: ['typeorm_metadata'],
  });

  await agent.mountOnStandaloneServer(3310).start();
}

bootstrap();

```

## Failure Logs

```log

info: Successfully mounted on Standalone server (http://localhost:3310)
info: Schema was not updated since last run
info: [200] POST /forest/authentication - 1ms
info: [200] GET /forest/authentication/callback - 417ms
error: [500] GET /forest/typeorm_metadata - 91ms

===== An exception was raised =====
GET /forest/typeorm_metadata?{
 timezone: Europe/Paris,
 fields[typeorm_metadata]: database,name,schema,table,type,value,
 page[number]: 1,
 page[size]: 15
}

 Failed Dependency 

Error: Failed Dependency
    at Request.callback (<path>/node_modules/superagent/src/node/index.js:900:17)
    at fn (<path>/node_modules/superagent/src/node/index.js:1153:18)
    at IncomingMessage.<anonymous> (<path>/node_modules/superagent/src/node/parsers/json.js:19:7)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
===================================

error: [500] GET /forest/typeorm_metadata/count - 0ms

===== An exception was raised =====
GET /forest/typeorm_metadata/count?{
 fields[typeorm_metadata]: database,name,schema,table,type,value,
 timezone: Europe/Paris
}

 Failed Dependency 

Error: Failed Dependency
    at Request.callback (<path>/node_modules/superagent/src/node/index.js:900:17)
    at fn (<path>/node_modules/superagent/src/node/index.js:1153:18)
    at IncomingMessage.<anonymous> (<path>/node_modules/superagent/src/node/parsers/json.js:19:7)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
===================================
```

## Context

- Package Version:
```
 - "@forestadmin/agent": "^1.4.1",
 - "@forestadmin/datasource-sql": "^1.1.4",
```

- forestadmin.schema.json
```json
[
  {
    "actions": [],
    "fields": [
      {
        "defaultValue": null,
        "enums": null,
        "field": "database",
        "integration": null,
        "inverseOf": null,
        "isFilterable": true,
        "isPrimaryKey": false,
        "isReadOnly": false,
        "isRequired": false,
        "isSortable": true,
        "isVirtual": false,
        "reference": null,
        "type": "String",
        "validations": []
      },
      {
        "defaultValue": null,
        "enums": null,
        "field": "name",
        "integration": null,
        "inverseOf": null,
        "isFilterable": true,
        "isPrimaryKey": false,
        "isReadOnly": false,
        "isRequired": false,
        "isSortable": true,
        "isVirtual": false,
        "reference": null,
        "type": "String",
        "validations": []
      },
      {
        "defaultValue": null,
        "enums": null,
        "field": "schema",
        "integration": null,
        "inverseOf": null,
        "isFilterable": true,
        "isPrimaryKey": false,
        "isReadOnly": false,
        "isRequired": false,
        "isSortable": true,
        "isVirtual": false,
        "reference": null,
        "type": "String",
        "validations": []
      },
      {
        "defaultValue": null,
        "enums": null,
        "field": "table",
        "integration": null,
        "inverseOf": null,
        "isFilterable": true,
        "isPrimaryKey": false,
        "isReadOnly": false,
        "isRequired": false,
        "isSortable": true,
        "isVirtual": false,
        "reference": null,
        "type": "String",
        "validations": []
      },
      {
        "defaultValue": null,
        "enums": null,
        "field": "type",
        "integration": null,
        "inverseOf": null,
        "isFilterable": true,
        "isPrimaryKey": false,
        "isReadOnly": false,
        "isRequired": true,
        "isSortable": true,
        "isVirtual": false,
        "reference": null,
        "type": "String",
        "validations": [
          {"type": "is present", "message": "Failed validation rule: 'Present'"}
        ]
      },
      {
        "defaultValue": null,
        "enums": null,
        "field": "value",
        "integration": null,
        "inverseOf": null,
        "isFilterable": true,
        "isPrimaryKey": false,
        "isReadOnly": false,
        "isRequired": false,
        "isSortable": true,
        "isVirtual": false,
        "reference": null,
        "type": "String",
        "validations": []
      }
    ],
    "icon": null,
    "integration": null,
    "isReadOnly": false,
    "isSearchable": true,
    "isVirtual": false,
    "name": "typeorm_metadata",
    "onlyForRelationships": false,
    "paginationType": "page",
    "segments": []
  }
]
```

**Comment by jeffladiray** [comment]
Hey @ajubin :wave:

Could you share with me the name of your project (So I can check your project configuration)?

If you are migrating from v1 to v2, I would highly suggest to create a new project instead of trying to migrate from our old to our new agent during your development phase.

`Failed dependency` (HTTP 424) seems to indicate that the project you are trying to use is currently not compatible with our Role ACL feature.

**Comment by ajubin** [comment]
So you're suggestion is to setup a new forest-admin org ?

My project is Muzzo :)

**Comment by jeffladiray** [comment]
Sorry, my answer was a little bit confusing 😓 

You can find more infos regarding the process to follow to fix this issue [here](https://community.forestadmin.com/t/receiving-424-failed-dependency-errors-on-forest-express-mongoose-when-upgraded-to-any-of-the-v9-variants/5612), on our discourse community
